modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"

[[mods]]
modId = "iris"

version = "1.8.0+mc1.20.1"
displayName = "Iris"

logoFile="assets/iris/iris-logo.png" #optional

authors="coderbot, IMS212, Justsnoopy30, FoundationGames"

description = '''
A modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs.
'''

[[mods]]
modId = "oculus"
version = "Stub"
displayName = "Iris-OculusStub"
description = '''
Stub for Oculus
'''

[mods."sodium:options"]
"mixin.features.render.world.sky"=false
"mixin.features.render.entity"=false
"mixin.features.render.gui.font"=false
